In [1]:
#import libraries
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

In [2]:
#load imdb dataset from keras
from keras.datasets import imdb

#split the dataset into train and test of reviews data and its labels
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

17464789/17464789 [==============================] - 0s 0us/step


In [17]:
train_data[:2]

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1153, 194, 8255, 78, 228,

In [4]:
train_labels[:20]

array([1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1])

In [9]:
'''
#get the word index
word_index = imdb.get_word_index()

#get the key, values of word index
reviews_data_dict = dict([(value, key) for (key, value) in word_index.items()])

#convert the reviews data into text form
reviews_data = ' '.join([reviews_data_dict.get(i - 3, '?') for i in train_data[0]])
'''

1641221/1641221 [==============================] - 0s 0us/step


In [5]:
#set independent data (reviews data) by vectorize into 0 and 1
def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.0
    return results

X_train = vectorize_sequences(train_data)
X_test = vectorize_sequences(test_data)

In [6]:
X_train

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.]])

In [7]:
#set dependent data (labels data)
Y_train = np.asanyarray(train_labels).astype('float32')
Y_test = np.asanyarray(test_labels).astype('float32')

In [8]:
Y_train

array([1., 0., 0., ..., 0., 1., 0.], dtype=float32)

In [9]:
#define neural network model structure
model = Sequential()
model.add(Dense(32, activation='relu', input_shape=(10000,)))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                320032    
                                                                 
 dense_1 (Dense)             (None, 16)                528       
                                                                 
 dense_2 (Dense)             (None, 1)                 17        
                                                                 
Total params: 320577 (1.22 MB)
Trainable params: 320577 (1.22 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [10]:
#compile the model
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])
X_val = X_train[:10000]
Y_val = Y_train[:10000]

In [18]:
#train the model with 20 epochs
model.fit(X_train, Y_train, epochs=20, batch_size=512, validation_data=(X_val, Y_val))

Epoch 1/20
49/49 [==============================] - 5s 89ms/step - loss: 0.0136 - accuracy: 0.9966 - val_loss: 0.0054 - val_accuracy: 0.9996
Epoch 2/20
49/49 [==============================] - 2s 43ms/step - loss: 0.0114 - accuracy: 0.9971 - val_loss: 0.0045 - val_accuracy: 0.9998
Epoch 3/20
49/49 [==============================] - 2s 38ms/step - loss: 0.0136 - accuracy: 0.9963 - val_loss: 0.0035 - val_accuracy: 0.9998
Epoch 4/20
49/49 [==============================] - 2s 44ms/step - loss: 0.0103 - accuracy: 0.9974 - val_loss: 0.0031 - val_accuracy: 0.9999
Epoch 5/20
49/49 [==============================] - 2s 37ms/step - loss: 0.0059 - accuracy: 0.9984 - val_loss: 0.0753 - val_accuracy: 0.9678
Epoch 6/20
49/49 [==============================] - 3s 60ms/step - loss: 0.0047 - accuracy: 0.9993 - val_loss: 0.0752 - val_accuracy: 0.9664
Epoch 7/20
49/49 [==============================] - 3s 53ms/step - loss: 0.0055 - accuracy: 0.9986 - val_loss: 0.0016 - val_accuracy: 1.0000
Epoch 8/20
49

In [12]:
#evaluate the model
result = model.evaluate(X_test, Y_test)
print("Evaluation results:")
print("Loss:", result[0])
print("Accuracy:", result[1]*100)

782/782 [==============================] - 2s 2ms/step - loss: 0.6587 - accuracy: 0.8583
Evaluation results:
Loss: 0.6586588025093079
Accuracy: 85.82800030708313
